import { PrismaClient } from "@/generated/prisma";

export const metadata = {
  title: "Dashboard - Mind Mesh",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
    Dashboard
    </>
  );
}
