import { getServerSession } from "next-auth"; 
import { authOptions } from "@/lib/auth";
import ErrorPage from "../auth/error/page";

export const metadata = {
  title: "Dashboard - Mind Mesh",
  description: "Generated by create next app",
};

export default async function Dashboard() {

  const session = await getServerSession(authOptions);
  if (!session) {
    return (
      <ErrorPage/>
    );
  }

  return (
    <>
    Dashboard
    </>
  );
}
